version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "5001:5001"

  user_service:
    build:
      context: ./user_service
    ports:
      - "5002:5002"

  notification_service:
    build:
      context: ./notification_service
    ports:
      - "5003:5003"

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
